modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="half_lived_crisis"
version="1.0.0"
displayName="Half Lived Crisis"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Puglord, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.half_lived_crisis]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"


[[dependencies.half_lived_crisis]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

